# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: MSBuild


on:
  #push:
    #branches: [ "main" ]
  #pull_request:
    #branches: [ "main" ]
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      tag_name:
        description: 'random info here'
        required: false

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/checkout@v4
      with:
        repository: audiosdk/asio
        path: asio_sdk_temp
      
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Place ASIO common folder
      working-directory: ${{env.GITHUB_WORKSPACE}}
      shell: powershell
      run: Copy-Item -Path "./asio_sdk_temp/common" -Destination "./src/uac2-asio/asio" -Recurse -Force

    - name: Setup Driver env
      working-directory: ${{env.GITHUB_WORKSPACE}}
      shell: powershell
      run: |
        # Download configuration file to install WDK with VS 2022 Community
        Invoke-WebRequest -Uri 'https://raw.githubusercontent.com/microsoft/Windows-driver-samples/main/configuration.dsc.yaml' -OutFile configuration.dsc.yaml

        # Install VS, SDK, WDK and WDK VS extension using the configuration file
        winget configure -f configuration.dsc.yaml
        
    - uses: humbletim/vsdevenv-shell@v2

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      shell: vsdevenv x64 powershell {0}
      run: .\build\build.ps1
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: compiles-${{matrix.configuration}}
        path: build\release\x64\Release
        retention-days: 3
